name: Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme

on:
  workflow_dispatch:

jobs:
  AA-GetData:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed


      - name: install python packages
        run: |
          cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: |
          cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme
          python Scripts/aa_getdata.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m " - Update Data" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
  
  TRT-GetData:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: Change File
        run: cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme

      - name: install python packages
        run: |
          cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: |
          cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme
          python Scripts/trt_getdata.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m " - Update Data" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
   
  NTV-GetData:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: Change File
        run: cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme

      - name: install python packages
        run: |
          cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: |
          cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme
          python Scripts/ntv_getdata.py
      
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m " - Update Data" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
  
  HURRIYET-GetData:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: Change File
        run: cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme

      - name: install python packages
        run: |
          cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: |
          cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme
          python Scripts/hurriyet_getdata.py
      
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m " - Update Data" --allow-empty)
      
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

  CNN-GetData:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: Change File
        run: cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme

      - name: install python packages
        run: |
          cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: |
          cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme
          python Scripts/cnn_getdata.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m " - Update Data" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

  Anka-GetData:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: Change File
        run: cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme

      - name: install python packages
        run: |
          cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: |
          cd Secim_2024_Haber_Kaynaklar覺ndan_Veri_ekme
          python Scripts/anka_getdata.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m " - Update Data" --allow-empty)
      
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main